Repository FiligranHQ/xtm-hub, pull requests merged in 2025-08, with the labels that each got.

#820 [frontend] ui: Improve toasters #816
  apps/portal-front/src/components/profile/index.tsx
Labels: Filigran Team

#827 chore(infra): remove Elasticsearch ingress monitoring annotation
  chart/templates/elasticsearch-ingress.yaml
Labels: Filigran Team

#804 [frontend] feat(1ClickDeploy CSV): display new buttons #525
  apps/portal-front/messages/en.json
  apps/portal-front/src/components/service/document/one-click-deploy/choose-platform-form.tsx
  apps/portal-front/src/components/service/document/one-click-deploy/one-click-deploy.tsx
  apps/portal-front/src/components/service/document/shareable-resource-slug.test.tsx
  apps/portal-front/src/components/service/document/shareable-resource-slug.tsx
  apps/portal-front/src/utils/constant.ts
Labels: Filigran Team, needs feature env

#797 [backend] feat: add query to check OpenCTI platform enrollment status
  apps/portal-api/src/__generated__/resolvers-types.ts
  apps/portal-api/src/modules/services/contract/domain.ts
  apps/portal-api/src/modules/services/enrollment/enrollment.app.test.ts
  apps/portal-api/src/modules/services/enrollment/enrollment.app.ts
  apps/portal-api/src/modules/services/enrollment/enrollment.graphql
  apps/portal-api/src/modules/services/enrollment/enrollment.resolver.ts
  apps/portal-front/app/(embed)/layout.tsx
  apps/portal-front/schema.graphql
  apps/portal-front/src/components/enroll/form/organization.tsx
  apps/portal-front/src/components/enroll/state/layout.tsx
  apps/portal-front/src/components/service/document/one-click-deploy/choose-platform-form.tsx
Labels: Filigran Team

#583 [backend] refactor: use user edition app in user resolver
  apps/portal-api/src/modules/common/error-code.ts
  apps/portal-api/src/modules/users/users.admin.app.ts
  apps/portal-api/src/modules/users/users.domain.ts
  apps/portal-api/src/modules/users/users.profile.app.ts
  apps/portal-api/src/modules/users/users.resolver.ts
Labels: Filigran Team, needs feature env

#829 [backend] - fix(dates) Change dates into dateTime #519
  apps/portal-api/src/migrations/20250805083254_pass_date_into_datetime.js
  apps/portal-api/src/model/kanel/public/ActionTracking.ts
  apps/portal-api/src/model/kanel/public/CapabilityPortal.ts
  apps/portal-api/src/model/kanel/public/Document.ts
  apps/portal-api/src/model/kanel/public/DocumentMetadata.ts
  apps/portal-api/src/model/kanel/public/GenericServiceCapability.ts
  apps/portal-api/src/model/kanel/public/Label.ts
  apps/portal-api/src/model/kanel/public/MessageTracking.ts
  apps/portal-api/src/model/kanel/public/Migrations.ts
  apps/portal-api/src/model/kanel/public/MigrationsLock.ts
  apps/portal-api/src/model/kanel/public/ObjectLabel.ts
  apps/portal-api/src/model/kanel/public/Organization.ts
  apps/portal-api/src/model/kanel/public/RolePortal.ts
  apps/portal-api/src/model/kanel/public/RolePortalCapabilityPortal.ts
  apps/portal-api/src/model/kanel/public/ServiceCapability.ts
  apps/portal-api/src/model/kanel/public/ServiceDefinition.ts
  apps/portal-api/src/model/kanel/public/ServiceInstance.ts
  apps/portal-api/src/model/kanel/public/ServiceLink.ts
  apps/portal-api/src/model/kanel/public/ServicePrice.ts
  apps/portal-api/src/model/kanel/public/Subscription.ts
  apps/portal-api/src/model/kanel/public/SubscriptionCapability.ts
  apps/portal-api/src/model/kanel/public/User.ts
  apps/portal-api/src/model/kanel/public/UserOrganization.ts
  apps/portal-api/src/model/kanel/public/UserOrganizationCapability.ts
  apps/portal-api/src/model/kanel/public/UserOrganizationPending.ts
  apps/portal-api/src/model/kanel/public/UserRolePortal.ts
  apps/portal-api/src/model/kanel/public/UserService.ts
  apps/portal-api/src/model/kanel/public/UserServiceCapability.ts
Labels: Filigran Team

#821 [backend/frontend] refactor: replace enroll by register in translations
  apps/portal-api/src/modules/common/error-code.ts
  apps/portal-api/src/modules/services/enrollment/enrollment.app.test.ts
  apps/portal-api/src/modules/services/enrollment/enrollment.app.ts
  apps/portal-api/src/modules/services/enrollment/enrollment.resolver.ts
  apps/portal-front/messages/en.json
  apps/portal-front/messages/fr.json
Labels: Filigran Team

#823 [backend/frontend] refactor: rename manage octi capability
  apps/portal-api/src/__generated__/resolvers-types.ts
  apps/portal-api/src/migrations/20250804144219_update-manage-octi-capability-name.js
  apps/portal-api/src/modules/services/enrollment/enrollment.app.ts
  apps/portal-api/src/modules/users/users.domain.ts
  apps/portal-api/src/modules/users/users.resolver.test.ts
  apps/portal-api/src/nodes/node.graphql
  apps/portal-api/src/security/auth.helper.test.ts
  apps/portal-front/messages/en.json
  apps/portal-front/messages/fr.json
  apps/portal-front/schema.graphql
  apps/portal-front/src/components/enroll/state/missing-capability.tsx
  apps/portal-front/src/components/unenroll/octi/missing-capability.tsx
  apps/portal-front/src/hooks/useOrganizationCapabilities.tsx
Labels: Filigran Team

#811 [frontend] styles(enrollment): better design for instance card
  apps/portal-front/messages/en.json
  apps/portal-front/messages/fr.json
  apps/portal-front/public/octi-private-platform-illustration.png
  apps/portal-front/public/octi-private-platform-logo.png
  apps/portal-front/src/components/service/service-instance-card.tsx
Labels: Filigran Team, needs feature env

#837 [backend/frontend] refactor: rename enroll and octi to register and OpenCTI
  apps/portal-api/src/__generated__/resolvers-types.ts
  apps/portal-api/src/migrations/20250807115950_rename-enrollment-service-definition.js
  apps/portal-api/src/migrations/20250807121132_update-registration-config-schema.js
  apps/portal-api/src/modules/common/error-code.ts
  apps/portal-api/src/modules/services/contract/domain.test.ts
  apps/portal-api/src/modules/services/definition/service-definition.graphql
  apps/portal-api/src/modules/services/enrollment/enrollment.graphql
  apps/portal-api/src/modules/services/instances/domain.ts
  apps/portal-api/src/modules/services/registration/registration.app.test.ts
  apps/portal-api/src/modules/services/registration/registration.app.ts
  apps/portal-api/src/modules/services/registration/registration.domain.test.ts
  apps/portal-api/src/modules/services/registration/registration.domain.ts
  apps/portal-api/src/modules/services/registration/registration.graphql
  apps/portal-api/src/modules/services/registration/registration.resolver.ts
  apps/portal-api/src/modules/tracking/tracking.domain.ts
  apps/portal-api/src/server/graphql-schema.ts
  apps/portal-front/app/(application)/app/page.tsx
  apps/portal-front/app/(embed)/register/opencti/page-loader.tsx
  apps/portal-front/app/(embed)/register/opencti/page.tsx
  apps/portal-front/app/(embed)/unregister/opencti/page-loader.tsx
  apps/portal-front/app/(embed)/unregister/opencti/page.tsx
  apps/portal-front/app/redirect/[identifier]/register-opencti.ts
  apps/portal-front/app/redirect/[identifier]/route.ts
  apps/portal-front/app/redirect/[identifier]/unregister-opencti.ts
  apps/portal-front/messages/en.json
  apps/portal-front/messages/fr.json
  apps/portal-front/schema.graphql
  apps/portal-front/src/components/enroll/enroll.graphql.ts
  apps/portal-front/src/components/enroll/octi.tsx
  apps/portal-front/src/components/register/form/organization.tsx
  apps/portal-front/src/components/register/never-registered.tsx
  apps/portal-front/src/components/register/opencti.tsx
  apps/portal-front/src/components/register/register.graphql.ts
  apps/portal-front/src/components/register/state/layout.tsx
  apps/portal-front/src/components/register/state/missing-capability.tsx
  apps/portal-front/src/components/service/document/one-click-deploy/one-click-deploy.tsx
  apps/portal-front/src/components/service/home/hooks/useServiceQueries.ts
  apps/portal-front/src/components/service/home/owned-services.tsx
  apps/portal-front/src/components/service/service-instance-card.tsx
  apps/portal-front/src/components/service/service-list.tsx
  apps/portal-front/src/components/unenroll/octi/index.tsx
  apps/portal-front/src/components/unenroll/octi/platform-not-enrolled.tsx
  apps/portal-front/src/components/unregister/opencti/confirm.tsx
  apps/portal-front/src/components/unregister/opencti/index.tsx
  apps/portal-front/src/components/unregister/opencti/missing-capability.tsx
  apps/portal-front/src/components/unregister/opencti/platform-not-registered.tsx
  apps/portal-front/src/utils/services.ts
Labels: Filigran Team

#830 [backend/frontend] chore: remove feature flags for release
  apps/portal-front/app/redirect/[identifier]/register-opencti.ts
  apps/portal-front/app/redirect/[identifier]/unregister-opencti.ts
  apps/portal-front/src/components/service/document/one-click-deploy/one-click-deploy.tsx
  apps/portal-front/src/components/service/document/shareable-resource-slug.test.tsx
  apps/portal-front/src/components/service/document/shareable-resource-slug.tsx
  apps/portal-front/src/hooks/useOrganizationCapabilities.tsx
  apps/portal-front/src/utils/constant.ts
Labels: Filigran Team, needs feature env

#858 [backend] - fix(pendingUser) delete migration script that fails with anonymized data #470
  apps/portal-api/src/migrations/20250812080113_add_users_to_pending.js
Labels: Filigran Team, needs feature env

#860 [backend] - feature(pendingUser) add feature flag #470
  apps/portal-front/src/components/admin/user/user-list-page.tsx
  apps/portal-front/src/utils/constant.ts
Labels: Filigran Team

#859 [backend/frontend] feat: add ability to download document with new token
  apps/portal-api/src/__generated__/resolvers-types.ts
  apps/portal-api/src/migrations/20250813132617_add-user-platform-token.js
  apps/portal-api/src/model/kanel/public/User.ts
  apps/portal-api/src/modules/common/error-code.ts
  apps/portal-api/src/modules/services/document/document-download-endpoint.ts
  apps/portal-api/src/modules/services/registration/registration.app.test.ts
  apps/portal-api/src/modules/services/registration/registration.app.ts
  apps/portal-api/src/modules/services/registration/registration.graphql
  apps/portal-api/src/modules/services/registration/registration.resolver.ts
  apps/portal-api/src/modules/users/users.graphql
  apps/portal-front/schema.graphql
  apps/portal-front/src/components/register/register.graphql.ts
  apps/portal-front/src/components/service/document/one-click-deploy/one-click-deploy.tsx
  apps/portal-front/src/components/service/document/one-click-deploy/one-platform-display.tsx
  apps/portal-front/src/components/service/document/one-click-deploy/useOneClickDeployTab.tsx
  apps/portal-front/src/hooks/useExternalTab.tsx
Labels: needs feature env

#836 [backend/frontend]: improve way to get service and add OBAS Scenario email #579 #843
  apps/portal-api/src/__generated__/resolvers-types.ts
  apps/portal-api/src/modules/services/definition/service-capability/service-capability.domain.test.ts
  apps/portal-api/src/modules/services/definition/service-capability/service-capability.domain.ts
  apps/portal-api/src/modules/services/definition/service-definition.resolver.test.ts
  apps/portal-api/src/modules/services/definition/service-definition.resolver.ts
  apps/portal-api/src/modules/services/document/visualize-document-endpoint.ts
  apps/portal-api/src/modules/services/service-instance.app.test.ts
  apps/portal-api/src/modules/services/service-instance.app.ts
  apps/portal-api/src/modules/services/service-instance.domain.ts
  apps/portal-api/src/modules/services/services.resolver.ts
  apps/portal-api/src/modules/subcription/subscription.resolver.test.ts
  apps/portal-api/src/modules/subcription/subscription.resolver.ts
  apps/portal-api/src/modules/user_service/user-service.helper.ts
  apps/portal-api/src/modules/user_service/user_service.graphql
  apps/portal-api/src/modules/user_service/user_service.resolver.ts
  apps/portal-api/src/modules/users/users.resolver.test.ts
  apps/portal-api/src/security/access.ts
  apps/portal-api/src/security/document-security-access.ts
  apps/portal-api/src/security/layer/service-definition.ts
  apps/portal-api/src/security/layer/service-instance.ts
  apps/portal-api/src/server/graphql-schema.ts
  apps/portal-api/src/server/mail-template/mail.ts
  apps/portal-api/src/server/mail-template/obas_scenarios.html
  apps/portal-api/tests/config-test.ts
  apps/portal-api/tests/setup-test.ts
  apps/portal-front/app/(application)/app/(user)/manage/service/[serviceInstanceId]/subscription/[subscriptionId]/page-loader.tsx
  apps/portal-front/app/(application)/app/(user)/manage/service/[serviceInstanceId]/subscription/[subscriptionId]/page.tsx
  apps/portal-front/app/(application)/app/(user)/service/csv_feeds/[serviceInstanceId]/[documentId]/page-loader.tsx
  apps/portal-front/app/(application)/app/(user)/service/csv_feeds/[serviceInstanceId]/[documentId]/page.tsx
  apps/portal-front/app/(application)/app/(user)/service/csv_feeds/[serviceInstanceId]/page.tsx
  apps/portal-front/app/(application)/app/(user)/service/custom_dashboards/[serviceInstanceId]/[documentId]/page-loader.tsx
  apps/portal-front/app/(application)/app/(user)/service/custom_dashboards/[serviceInstanceId]/[documentId]/page.tsx
  apps/portal-front/app/(application)/app/(user)/service/custom_dashboards/[serviceInstanceId]/page.tsx
  apps/portal-front/app/(application)/app/(user)/service/obas_scenarios/[serviceInstanceId]/[documentId]/page-loader.tsx
  apps/portal-front/app/(application)/app/(user)/service/obas_scenarios/[serviceInstanceId]/[documentId]/page.tsx
  apps/portal-front/app/(application)/app/(user)/service/obas_scenarios/[serviceInstanceId]/page.tsx
  apps/portal-front/app/(application)/app/(user)/service/vault/[slug]/page-loader.tsx
  apps/portal-front/app/(application)/app/(user)/service/vault/[slug]/page.tsx
  apps/portal-front/schema.graphql
  apps/portal-front/src/components/service/service.graphql.ts
  apps/portal-front/src/components/service/vault/[slug]/document-list.tsx
  apps/portal-front/src/components/subcription/[slug]/subscription-slug.tsx
Labels: Filigran Team, needs feature env

#887 [backend] - fix(elasticsearch/kibana): change port to avoid conflicts with opencti and openbas #634
  apps/portal-api/config/default.json
  xtm-hub-dev/docker-compose.yml
Labels: Filigran Team
